name: CI-8.0

on:
  push:
    paths:
      - '.github/workflows/ci-8.0.yml'
      - 'src/**'
      - 'tests/**'
      - 'example/**'
      - 'composer.json'
      - 'composer.lock'
    branches:
      - '!*'
      - 'develop'
      - 'stage'
      - 'master'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-suggest --ignore-platform-reqs

      - name: Test
        run: |
          composer check-style && composer test-cov
