name: CI7.4

on:
  push:
    paths:
      - '.github/workflows/ci7.4.yml'
      - 'src/**'
      - 'tests/**'
      - 'example/**'
      - 'composer.json'
      - 'composer.lock'
    branches:
      - '!*'
      - 'develop'
      - 'stage'
      - 'master'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-suggest --ignore-platform-reqs

      - name: Install PHP7.4 dependencies
        run: |
            composer require psr/log:^1 --ignore-platform-reqs --with-all-dependencies
            composer require --dev phpunit/phpunit:^8 --ignore-platform-reqs --with-all-dependencies

      - name: Test
        run: |
          composer check-style && composer test-cov

